import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";  // Use Inter or any valid font
import "./globals.css";

// Replace Geist and Geist_Mono with Inter or any other font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} antialiased`}  // Use the updated font classes here
      >
        {children}
      </body>
    </html>
  );
}
