import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google"; // Correct fonts from Google
import "./globals.css";

// Replace Geist and Geist_Mono with valid fonts like Inter or Roboto
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ['400', '700'],  // Specify weights for Roboto font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} antialiased`}  // Make sure to use these updated fonts
      >
        {children}
      </body>
    </html>
  );
}
